-- Insert sample temples tied to public images
INSERT INTO public.temples (name, location, state, deity, category, rating, review_count, image, description, history, best_time_to_visit, opening_time, closing_time, entry_fee, dress_code, rituals, festivals)
VALUES
  (
    'Tirupati Balaji Temple',
    'Tirumala, Tirupati',
    'Andhra Pradesh',
    'Lord Venkateswara',
    'Vishnu',
    4.8,
    15420,
    '/tirupati-balaji-temple.jpg',
    'One of the richest and most visited temples in the world, dedicated to Lord Venkateswara.',
    'The temple has a rich history dating back over 2000 years. It is believed that Lord Venkateswara appeared here to save mankind from the trials of Kali Yuga.',
    'September to February',
    '02:30:00',
    '01:00:00',
    'Free (Special Darshan: INR 300)',
    'Traditional attire required',
    ARRAY['Suprabhatam', 'Thomala Seva', 'Archana'],
    ARRAY['Brahmotsavam', 'Vaikunta Ekadasi']
  ),
  (
    'Golden Temple',
    'Amritsar',
    'Punjab',
    'Guru Granth Sahib',
    'Sikh',
    4.9,
    22100,
    '/golden-temple-amritsar.jpg',
    'The holiest Gurdwara of Sikhism, known for its golden dome and spiritual significance.',
    'Built in 1577 by Guru Ram Das, the temple stands as a symbol of equality and brotherhood.',
    'October to March',
    '00:00:00',
    '23:59:00',
    'Free',
    'Head covering mandatory',
    ARRAY['Kirtan', 'Langar Seva'],
    ARRAY['Guru Nanak Jayanti', 'Baisakhi']
  ),
  (
    'Vaishno Devi Temple',
    'Katra',
    'Jammu and Kashmir',
    'Goddess Vaishno Devi',
    'Shakti',
    4.7,
    18500,
    '/vaishno-devi-temple.jpg',
    'One of the most revered Hindu temples dedicated to Goddess Vaishno Devi.',
    'The cave temple is believed to be the sacred abode where the Goddess meditated.',
    'March to October',
    '05:00:00',
    '22:00:00',
    'Free',
    'Modest clothing required',
    ARRAY['Aarti', 'Bhog'],
    ARRAY['Navratri', 'Diwali']
  ),
  (
    'Meenakshi Temple',
    'Madurai',
    'Tamil Nadu',
    'Goddess Meenakshi',
    'Shakti',
    4.8,
    12800,
    '/meenakshi-temple-madurai.jpg',
    'A historic Hindu temple dedicated to Goddess Meenakshi and Lord Sundareshwarar.',
    'The temple dates back to the 6th century and showcases Dravidian architecture.',
    'October to March',
    '05:00:00',
    '22:00:00',
    'INR 50',
    'Traditional attire preferred',
    ARRAY['Abhishekam', 'Kumkum Puja'],
    ARRAY['Meenakshi Thirukalyanam', 'Float Festival']
  ),
  (
    'Jagannath Temple',
    'Puri',
    'Odisha',
    'Lord Jagannath',
    'Vishnu',
    4.7,
    14200,
    '/jagannath-temple-puri.jpg',
    'One of the Char Dham pilgrimage sites, famous for its annual Rath Yatra.',
    'The temple was built in the 12th century and is an important pilgrimage site.',
    'October to February',
    '05:00:00',
    '22:00:00',
    'Free',
    'Only Hindus allowed',
    ARRAY['Mangala Aarti', 'Sandhya Aarti'],
    ARRAY['Rath Yatra', 'Snana Yatra']
  ),
  (
    'Kashi Vishwanath Temple',
    'Varanasi',
    'Uttar Pradesh',
    'Lord Shiva',
    'Shiva',
    4.8,
    13200,
    '/kashi-vishwanath-temple-varanasi.jpg',
    'One of the twelve Jyotirlingas, situated on the banks of the Ganges.',
    'The temple has been rebuilt several times, with the current structure commissioned by Ahilyabai Holkar in 1780.',
    'October to March',
    '03:00:00',
    '23:00:00',
    'Free (Special Darshan: INR 300)',
    'Traditional attire preferred',
    ARRAY['Mangala Aarti', 'Shringar Aarti', 'Bhog Aarti'],
    ARRAY['Maha Shivaratri', 'Dev Deepawali']
  ),
  (
    'South Gopuram Temple',
    'Thanjavur',
    'Tamil Nadu',
    'Lord Shiva',
    'Dravidian',
    4.6,
    8700,
    '/beautiful-indian-temple-golden-hour.jpg',
    'A classic South Indian temple known for its towering gopuram glowing at golden hour.',
    'Built in the Chola era and expanded by successive dynasties, it remains a center for Shaivite traditions.',
    'November to February',
    '05:30:00',
    '21:30:00',
    'Free',
    'Traditional attire preferred',
    ARRAY['Rudrabhishek', 'Evening Aarti'],
    ARRAY['Margazhi Festival', 'Karthigai Deepam']
  )
ON CONFLICT DO NOTHING;
