-- Insert sample temples
INSERT INTO public.temples (name, location, state, deity, category, rating, review_count, image, description, history, best_time_to_visit, opening_time, closing_time, entry_fee, dress_code, rituals, festivals)
VALUES
  (
    'Tirupati Balaji Temple',
    'Tirumala, Tirupati',
    'Andhra Pradesh',
    'Lord Venkateswara',
    'Vishnu',
    4.8,
    15420,
    '/placeholder.svg?height=400&width=600',
    'One of the richest and most visited temples in the world, dedicated to Lord Venkateswara.',
    'The temple has a rich history dating back over 2000 years. It is believed that Lord Venkateswara appeared here to save mankind from the trials of Kali Yuga.',
    'September to February',
    '02:30:00',
    '01:00:00',
    'Free (Special Darshan: ₹300)',
    'Traditional attire required',
    ARRAY['Suprabhatam', 'Thomala Seva', 'Archana'],
    ARRAY['Brahmotsavam', 'Vaikunta Ekadasi']
  ),
  (
    'Golden Temple',
    'Amritsar',
    'Punjab',
    'Guru Granth Sahib',
    'Sikh',
    4.9,
    22100,
    '/placeholder.svg?height=400&width=600',
    'The holiest Gurdwara of Sikhism, known for its golden dome and spiritual significance.',
    'Built in 1577 by Guru Ram Das, the temple stands as a symbol of equality and brotherhood.',
    'October to March',
    '00:00:00',
    '23:59:00',
    'Free',
    'Head covering mandatory',
    ARRAY['Kirtan', 'Langar Seva'],
    ARRAY['Guru Nanak Jayanti', 'Baisakhi']
  ),
  (
    'Vaishno Devi Temple',
    'Katra',
    'Jammu & Kashmir',
    'Goddess Vaishno Devi',
    'Shakti',
    4.7,
    18500,
    '/placeholder.svg?height=400&width=600',
    'One of the most revered Hindu temples dedicated to Goddess Vaishno Devi.',
    'The cave temple is believed to be the sacred abode where the Goddess meditated.',
    'March to October',
    '05:00:00',
    '22:00:00',
    'Free',
    'Modest clothing required',
    ARRAY['Aarti', 'Bhog'],
    ARRAY['Navratri', 'Diwali']
  ),
  (
    'Meenakshi Temple',
    'Madurai',
    'Tamil Nadu',
    'Goddess Meenakshi',
    'Shakti',
    4.8,
    12800,
    '/placeholder.svg?height=400&width=600',
    'A historic Hindu temple dedicated to Goddess Meenakshi and Lord Sundareshwarar.',
    'The temple dates back to the 6th century and showcases Dravidian architecture.',
    'October to March',
    '05:00:00',
    '22:00:00',
    '₹50',
    'Traditional attire preferred',
    ARRAY['Abhishekam', 'Kumkum Puja'],
    ARRAY['Meenakshi Thirukalyanam', 'Float Festival']
  ),
  (
    'Jagannath Temple',
    'Puri',
    'Odisha',
    'Lord Jagannath',
    'Vishnu',
    4.7,
    14200,
    '/placeholder.svg?height=400&width=600',
    'One of the Char Dham pilgrimage sites, famous for its annual Rath Yatra.',
    'The temple was built in the 12th century and is an important pilgrimage site.',
    'October to February',
    '05:00:00',
    '22:00:00',
    'Free',
    'Only Hindus allowed',
    ARRAY['Mangala Aarti', 'Sandhya Aarti'],
    ARRAY['Rath Yatra', 'Snana Yatra']
  ),
  (
    'Kedarnath Temple',
    'Kedarnath',
    'Uttarakhand',
    'Lord Shiva',
    'Shiva',
    4.9,
    16700,
    '/placeholder.svg?height=400&width=600',
    'One of the twelve Jyotirlingas, located in the Garhwal Himalayas.',
    'The temple is believed to have been built by the Pandavas and revived by Adi Shankaracharya.',
    'May to October',
    '04:00:00',
    '21:00:00',
    'Free',
    'Warm clothing required',
    ARRAY['Rudrabhishek', 'Aarti'],
    ARRAY['Maha Shivaratri']
  ),
  (
    'Siddhivinayak Temple',
    'Mumbai',
    'Maharashtra',
    'Lord Ganesha',
    'Ganesha',
    4.6,
    9500,
    '/placeholder.svg?height=400&width=600',
    'A famous Ganesha temple known for fulfilling devotees wishes.',
    'Built in 1801, the temple attracts millions of devotees annually.',
    'November to February',
    '05:30:00',
    '22:00:00',
    'Free',
    'No restrictions',
    ARRAY['Aarti', 'Modak Offering'],
    ARRAY['Ganesh Chaturthi']
  ),
  (
    'Somnath Temple',
    'Prabhas Patan',
    'Gujarat',
    'Lord Shiva',
    'Shiva',
    4.7,
    11200,
    '/placeholder.svg?height=400&width=600',
    'The first among the twelve Jyotirlinga shrines of Shiva.',
    'The temple has been destroyed and rebuilt several times throughout history.',
    'October to March',
    '06:00:00',
    '21:00:00',
    'Free',
    'Traditional attire preferred',
    ARRAY['Rudrabhishek', 'Evening Aarti'],
    ARRAY['Maha Shivaratri', 'Kartik Purnima']
  )
ON CONFLICT DO NOTHING;
